openapi: 3.0.2
info:
  title: 'E-Commerce ALTA - Project 1 (Group : 2)'
  description: Open API Template
  contact:
    name: kelompok 2
    email: kelompok2@aja.com
  version: '1.0'
servers:
  - url: https://api.server.test/{version}
    variables:
      version:
        default: v1
        enum:
          - v1
          - v2
paths:
  /users/login:
    post:
      summary: Login Users
      tags:
        - Auth
      requestBody:
        required: true
        description: Please Login
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: test@test.com
                password:
                  type: string
                  example: '123456'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success Login
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: test
                      email:
                        type: string
                        example: test@test.com
                  token:
                    type: object
                    example: hbskbasua6t3286t87fg8ybibiesufbg9aey29f
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /users:
    get:
      summary: Get All Users
      tags:
        - Admin
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to get all users
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: integer
                        address:
                          type: object
                    example:
                      - id: 1
                        name: test
                        email: test@test.com
                        address: {}
                      - id: 2
                        name: test2
                        email: test2@test.com
                        address: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /users/register:
    post:
      summary: Register Users
      tags:
        - Users
      requestBody:
        required: true
        description: Input Parameters to Register
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: test
                email:
                  type: string
                  example: test@test.com
                password:
                  type: string
                  example: '123'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Resgister user
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: test
                      email:
                        type: string
                        example: test@test.com
                      password:
                        type: string
                        example: '123'
                      address:
                        type: object
                        properties: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /users/me:
    get:
      summary: Get User Profile
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get Profile
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: test
                      email:
                        type: string
                        example: test@test.com
                      password:
                        type: string
                        example: '123'
                      address:
                        type: object
                        properties: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update User
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TestListInput'
            example:
              name: updated_name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 1
                message: Berhasil ubah aktivitas
                data:
                  name: updated_name
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Delete User
      tags:
        - Users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: Success to delete Data
                data: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /category:
    post:
      summary: Register Category
      tags:
        - Category
      requestBody:
        required: true
        description: Input Parameters to Register
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: categories 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Create Category
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: categories 1
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Get All Categories
      tags:
        - Category
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get All Category
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                    example:
                      - id: 1
                        name: marvel
                      - id: 2
                        name: DC
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /category/{id}:
    get:
      summary: Get a Categories
      tags:
        - Category
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get Category
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: marvel
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update Category
      tags:
        - Category
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TestListInput'
            example:
              name: new name categories
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Update Category
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: new name category
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Delete Category
      tags:
        - Category
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: Success to delete Data
                data: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /products:
    post:
      summary: Register Products
      tags:
        - Products
      requestBody:
        required: true
        description: Input Data Products to Register
        content:
          application/json:
            schema:
              type: object
              properties:
                category_id:
                  type: integer
                  example: 1
                name:
                  type: string
                  example: barbatros
                price:
                  type: integer
                  example: 5000
                qty:
                  type: integer
                  example: 10
                description:
                  type: string
                  example: MG 1/100
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Sucess to register products
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      category_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: barbatros
                      price:
                        type: integer
                        example: 5000
                      qty:
                        type: integer
                        example: 10
                      description:
                        type: string
                        example: MG 1/100
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Get All Product
      tags:
        - Products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to get all product
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        email:
                          type: string
                        address:
                          type: string
                        rules_id:
                          type: integer
                    example:
                      - id: 1
                        category_id: 1
                        name: barbatros
                        price: 5000
                        qty: 10
                      - id: 2
                        category_id: 2
                        name: spiderman
                        price: 15000
                        qty: 5
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /products/{id}:
    get:
      summary: Get Product details
      tags:
        - Products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to get product details
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      category_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: barbatros
                      price:
                        type: integer
                        example: 5000
                      qty:
                        type: integer
                        example: 10
                      description:
                        type: string
                        example: MG 1/100
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TestListInput'
            example:
              name: updated_name_product
              qty: 25
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to get product details
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      category_id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: update_name_product
                      price:
                        type: integer
                        example: 5000
                      qty:
                        type: integer
                        example: 25
                      description:
                        type: string
                        example: MG 1/100
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    delete:
      tags:
        - Products
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: Success to delete Data
                data: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /carts:
    post:
      summary: Register Cart
      tags:
        - Cart
      requestBody:
        required: true
        description: Input Parameters to Register
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  product_id:
                    type: integer
                    example: 5
                  qty:
                    type: integer
                    example: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Create Cart
                  data:
                    type: object
                    properties:
                      cart_id:
                        type: integer
                        example: 1
                      product_id:
                        type: integer
                        example: 5
                      user_id:
                        type: integer
                        example: 1
                      qty:
                        type: integer
                        example: 2
                      total_price:
                        type: integer
                        example: 40000
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Get All Carts Detail
      tags:
        - Cart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get All Cart
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        cart_id:
                          type: integer
                        product_id:
                          type: integer
                        user_id:
                          type: integer
                        qty:
                          type: integer
                        total_price:
                          type: integer
                    example:
                      - cart_id: 1
                        product_id: 5
                        user_id: 1
                        qty: 2
                        total_price: 40000
                      - cart_id: 2
                        product_id: 2
                        user_id: 1
                        qty: 3
                        total_price: 65000
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /carts/{id}:
    get:
      summary: Get a Cart
      tags:
        - Cart
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get Cart
                  data:
                    type: object
                    properties:
                      cart_id:
                        type: integer
                        example: 1
                      product_id:
                        type: integer
                        example: 5
                      user_id:
                        type: integer
                        example: 1
                      qty:
                        type: integer
                        example: 2
                      total_price:
                        type: integer
                        example: 40000
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update Cart
      tags:
        - Cart
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TestListInput'
            example:
              qty: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Update Cart
                  data:
                    type: object
                    properties:
                      cart_id:
                        type: integer
                        example: 1
                      product_id:
                        type: integer
                        example: 5
                      user_id:
                        type: integer
                        example: 1
                      qty:
                        type: integer
                        example: 10
                      total_price:
                        type: integer
                        example: 100000
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Delete Cart
      tags:
        - Cart
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: Success to delete Data
                data: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /paymentmethods:
    post:
      summary: Register Payment Methods
      tags:
        - Payments
      requestBody:
        required: true
        description: Input Parameters to Register
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  name_methods:
                    type: string
                    example: ovo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Create Payment Methods
                  data:
                    type: object
                    properties:
                      payment_methods_id:
                        type: integer
                        example: 1
                      name_methods:
                        type: string
                        example: ovo
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Get All Payment Methods
      tags:
        - Payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get Payment Methods
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        payment_methods_id:
                          type: integer
                        name_methods:
                          type: string
                    example:
                      - payment_methods_id: 1
                        name_methods: ovo
                      - payment_methods_id: 2
                        name_methods: gopay
                      - payment_methods_id: 3
                        name_methods: dana
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /paymentmethods/{id}:
    get:
      summary: Get a Payment Methods
      tags:
        - Payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get Payment Method
                  data:
                    type: object
                    properties:
                      payment_methods_id:
                        type: integer
                        example: 1
                      name_methods:
                        type: string
                        example: ovo
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    put:
      summary: Update Payment Methods
      tags:
        - Payments
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/TestListInput'
            example:
              name: shopee pay
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Update Payment Methods
                  data:
                    type: object
                    properties:
                      payment_methods_id:
                        type: integer
                        example: 1
                      name_methods:
                        type: string
                        example: shopee
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    delete:
      summary: Delete Payment Methods
      tags:
        - Payments
      parameters:
        - name: id
          in: path
          description: User ID
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessSingleResponse'
              example:
                code: 200
                message: Success to delete Data
                data: {}
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /orders:
    post:
      summary: Register Orders
      tags:
        - Orders
      requestBody:
        required: true
        description: Input Parameters to Register
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 1
                  payment_methods_id:
                    type: integer
                    example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Create Cart
                  data:
                    type: object
                    properties:
                      order_id:
                        type: integer
                        example: 1
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
    get:
      summary: Get Detail Orders
      tags:
        - Orders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: Success to Get All Cart
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        cart_id:
                          type: integer
                        product_id:
                          type: integer
                        user_id:
                          type: integer
                        qty:
                          type: integer
                        total_price:
                          type: integer
                    example:
                      - order_id: 1
                      - order_id: 2
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
components:
  parameters:
    input:
      name: id
      in: path
      required: true
      schema:
        type: integer
  schemas:
    TestListInput:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
    SuccessSingleResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          $ref: '#/components/schemas/TestListInput'
  responses:
    '400':
      description: Invalid Input
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 400
              message:
                type: string
                example: invalid input
              data:
                type: object
    '500':
      description: Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 500
              message:
                type: string
                example: There are some problem in server
              data:
                type: object
